# Generated by Django 5.1.5 on 2026-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
