# Generated by Django 5.1.5 on 2026-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analysed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, help_text='What the AI decided this is.', max_length=60),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='suggested_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
