import uuid

from django.db import migrations, models


def assign_share_tokens(apps, schema_editor):
    """Give every existing goal its own token.

    Written by hand rather than autogenerated: a callable default on a unique
    column would hand every existing row the *same* UUID and then fail the
    constraint, so the column is added nullable, backfilled per row, and only
    then made unique.
    """
    Goal = apps.get_model("goals", "Goal")
    for goal in Goal.objects.filter(share_token__isnull=True).iterator():
        Goal.objects.filter(pk=goal.pk).update(share_token=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [("goals", "0002_task_completed_at")]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="share_token",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(assign_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="goal",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
