# Generated by Django 5.1.5 on 2026-08-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0003_goal_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resume', 'Résumé'), ('diet_plan', 'Diet plan'), ('timetable', 'Study timetable'), ('cover_letter', 'Cover letter'), ('project_report', 'Project report')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, help_text='What the user originally asked for.')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, help_text='Optional: the goal this document was made for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='studio_arti_user_id_b8d0e3_idx')],
            },
        ),
    ]
