# Generated by Django 5.1.5 on 2026-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='artifacts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('resume', 'Résumé'), ('diet_plan', 'Diet plan'), ('timetable', 'Study timetable'), ('cover_letter', 'Cover letter'), ('project_report', 'Project report'), ('invitation', 'Invitation card'), ('image', 'Generated image')], max_length=32),
        ),
    ]
