# Generated by Django 5.1.5 on 2026-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_artifact_image_alter_artifact_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('resume', 'Résumé'), ('diet_plan', 'Diet plan'), ('timetable', 'Study timetable'), ('cover_letter', 'Cover letter'), ('project_report', 'Project report'), ('invitation', 'Invitation card'), ('image', 'Generated image'), ('certificate', 'Certificate of completion')], max_length=32),
        ),
    ]
